services:
  gateway:
    build: ./gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gateway/lua:/usr/local/openresty/nginx/lua
    networks:
      - shared-auth-network

networks:
  shared-auth-network:
    name: shared-auth-network
    driver: bridge
